# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a8475b616633402d91ee0e4d293a17b4b260c0588374c59337e87d8dd105319ae5381b23ea11b1669c3848940a4ce508ca6aa753e07d60bd979d710e545287ae

test:
  secret_key_base: 56c9b3c6ba279a5c08fb165d58c5d1cbbac289836546af8289963ae278b51b4fe52568f0019e2d31d544ccf37dac2d93eaad7ce13d0ef69a1a30209f4442ccc8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
